### PR TITLE
Fix/handle funding info

### PR DESCRIPTION
**Pull request by ming0393639**
BitfinexSymbolOverview and BitfinexTradeSimple lost the properties of funding, so added them.
Please check, thanks.

### CODE REVIEW

**Comment by fieldfoxWim** [comment]
@JKorf What is the status of this PR?
Subscribing to the fEUR, .. symbols does not work properly atm,
This PR would fix that, is it possible to do a merge?

Thx for checking

**Comment by Captain12311** [comment]
Keep me updated, Please!!

Todd

**Comment by fieldfoxWim** [comment]
@ming0393639  any chance you can fix the merge conflicts?
they are purely located in the .XML documentation

**Comment by JKorf** [comment]
Just an update from my side; the Bitfinex API has been a bit neglected, but once I finish the Binance API update in a few days I'll start with a big update to the Bitfinex API to bring it up to date with the current API docs and make sure it all works as expected

**Comment by Captain12311** [comment]
Awesome, thanks for the update!

Todd

**Comment by ming0393639** [comment]
> @ming0393639 any chance you can fix the merge conflicts? they are purely located in the .XML documentation

@fieldfoxWim 
I have performed a simple merge on my fork without thoroughly checking.
Please use with caution, if you need it urgently.

**Comment by Captain12311** [comment]
When can website be used again?????

Todd

**Comment by JKorf** [comment]
In the latest update I've added separate endpoints for methods where both a trading and funding symbol are supported but the response models are different. I think everything should work as expected with that, if not let me know

**Comment by Captain12311** [comment]
Web address is still not found!! When will it be fixed.

Thanks

Todd

**Pull request closed without merging**
